### ISSUE TITLE
ichunutil

### ISSUE THREAD

**Issue by Valorum5** [iChun/iChunUtil#117]
I have been having issues with my Minecraft Server. I have other mods installed but they work when I take iChun's mods out. I am trying to get this server up ASAP. Please help.

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 6/24/16 10:02 AM
Description: Exception in server tick loop

Missing Mods:
	iChunUtil : [4.0.0,)

cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:243)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:493)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1991425056 bytes (1899 MB) / 2058354688 bytes (1963 MB) up to 2058354688 bytes (1963 MB)
	JVM Flags: 2 total; -Xms2048M -Xmx2048M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	U	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	U	thedalekmod{39.75} [The Dalek Mod] (Dalek_Mod_1710.jar) 
	U	MCA{1.7.10-5.1.2} [Minecraft Comes Alive] (MCA-1.7.10-5.1.2-universal.jar) 
	U	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	U	RadixCore{2.1.1} [RadixCore] (RadixCore-1.7.10-2.1.1-universal.jar) 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by iChun** [comment]
Missing Mods:
iChunUtil : [4.0.0,)

**Comment by Valorum5** [comment]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 6/24/16 11:09 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at net.minecraft.profiler.Profiler.func_76320_a(Profiler.java:64)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:546)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more
Caused by: java.lang.RuntimeException: Attempted to load class bjf for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 6 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1998379584 bytes (1905 MB) / 2136997888 bytes (2038 MB) up to 2136997888 bytes (2038 MB)
	JVM Flags: 2 total; -Xms2048M -Xmx2048M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	thedalekmod{39.75} [The Dalek Mod] (Dalek_Mod_1710.jar) 
	UCHIJAAAA	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) 
	UCHIJAAAA	RadixCore{2.1.1} [RadixCore] (RadixCore-1.7.10-2.1.1-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.1.2} [Minecraft Comes Alive] (MCA-1.7.10-5.1.2-universal.jar) 
	UCHIJAAAA	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by iChun** [comment]
Use the latest version that starts with a 4. I think it was 4.2.2 or
something. Don't use any that starts with 5.
