### ISSUE TITLE
1.10.2 - OpenEye

### ISSUE THREAD

**Issue by iChun** [iChun/iChunUtil#129]
https://openeye.openmods.info/crashes/2ad50c6d80ca744212870a2b5098bb86

java.lang.IndexOutOfBoundsException: Index: 20, Size: 0

    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at me.ichun.mods.ichunutil.common.core.tracker.EntityTrackerRegistry.tick(EntityTrackerRegistry.java:16)
    at me.ichun.mods.ichunutil.client.core.EntityTrackerHandler.tick(EntityTrackerHandler.java:78)
    at me.ichun.mods.ichunutil.client.core.event.EventHandlerClient.onClientTick(EventHandlerClient.java:229)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_0_EventHandlerClient_onClientTick_ClientTickEvent.invoke(.dynamic:-1)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)

**Comment by iChun** [comment]
Network Thread is clearing the list on client disconnect, Thread collision. Schedule a task to clear it on the main thread.
