### ISSUE TITLE
iChunUtil Crashing

### ISSUE THREAD

**Issue by wilson20cc** [iChun/iChunUtil#130]
All other mods work fine but when I try to use iChunUtil for your mods the game crashes at start up. I've uninstalled every other mod and just installed iChunUtil and it still crashes. Everything is at version 1.10.2. Here's the crash report:

---- Minecraft Crash Report ----
// Don't do that.

Time: 12/3/16 10:25 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.containsVersion(DefaultArtifactVersion.java:74)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.equals(DefaultArtifactVersion.java:56)
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:211)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.containsVersion(DefaultArtifactVersion.java:74)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.equals(DefaultArtifactVersion.java:56)
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:211)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.minecraftforge.fml.client.GuiModsMissing
	Mouse location: Scaled: (729, 320). Absolute: (1459, 439)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 694832304 bytes (662 MB) / 1697120256 bytes (1618 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2099 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2099.jar) 
	U	Forge{12.18.2.2099} [Minecraft Forge] (forge-1.10.2-12.18.2.2099.jar) 
	U	ichunutil{6.1.0} [iChunUtil] (iChunUtil-1.10.2-6.1.0.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 375.95' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.2.2099
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 375.95, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft 256x MC110
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz

**Comment by iChun** [comment]
This is a Minecraft Forge issue. I'll pass the issue on to them. 

In the meantime you should update Forge, iChunUtil requires a higher version of Forge and it's trying to tell you that but it's crashing when it does.
