### ISSUE TITLE
It crashes on load and makes no sence it says you must include the right dependensies for iChunUtil minecraft forge  

### ISSUE THREAD

**Issue by 123ab2** [iChun/iChunUtil#203]
log [20:26:19] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:26:19] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:26:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:26:19] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2768 for Minecraft 1.12.2 loading
[20:26:19] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64
[20:26:19] [main/INFO] [FML]: Searching C:\Users\Owner\AppData\Roaming\.minecraft\mods for mods
[20:26:19] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from betterportals-0.3.7.4.jar
[20:26:19] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:26:19] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:26:19] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[20:26:19] [main/WARN] [FML]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:26:19] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:26:19] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[20:26:19] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Owner/AppData/Roaming/.minecraft/mods/betterportals-0.3.7.4.jar Service=LaunchWrapper Env=CLIENT
[20:26:20] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:26:20] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:26:20] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:26:20] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:26:22] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[20:26:22] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[20:26:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:26:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:26:22] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[20:26:22] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[20:26:22] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@57b9e423
[20:26:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:26:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:26:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:26:23] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[20:26:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[20:26:23] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[20:26:23] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[20:26:24] [main/INFO] [net.minecraft.client.Minecraft]: Setting user: ILikeWoofles
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: lastServer:
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.pickItem:key.mouse.middle
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.playerlist:key.keyboard.tab
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.advancements:key.keyboard.l
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.5:key.keyboard.5
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.6:key.keyboard.6
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.7:key.keyboard.7
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.8:key.keyboard.8
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.1:key.keyboard.1
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.2:key.keyboard.2
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.3:key.keyboard.3
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.4:key.keyboard.4
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.sprint:key.keyboard.left.control
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.forward:key.keyboard.w
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.drop:key.keyboard.q
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.back:key.keyboard.s
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.attack:key.mouse.left
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.use:key.mouse.right
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.saveToolbarActivator:key.keyboard.c
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.smoothCamera:key.keyboard.unknown
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.right:key.keyboard.d
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.jump:key.keyboard.space
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.sneak:key.keyboard.left.shift
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.spectatorOutlines:key.keyboard.unknown
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.left:key.keyboard.a
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.command:key.keyboard.slash
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.screenshot:key.keyboard.f2
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.hotbar.9:key.keyboard.9
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.togglePerspective:key.keyboard.f5
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.chat:key.keyboard.t
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.inventory:key.keyboard.e
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.fullscreen:key.keyboard.f11
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.loadToolbarActivator:key.keyboard.x
[20:26:28] [main/WARN] [net.minecraft.client.settings.GameSettings]: Skipping bad option: key_key.swapHands:key.keyboard.f
[20:26:28] [main/INFO] [net.minecraft.client.Minecraft]: LWJGL Version: 2.9.4
[20:26:29] [main/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 566918992 bytes (540 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.4.jar)
  
RandomPatches (randompatches-1.12.2-1.20.1.0.jar)
  com.therandomlabs.randompatches.core.RPTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.6911' Renderer: 'Intel(R) UHD Graphics'
[20:26:29] [main/INFO] [FML]: MinecraftForge v14.23.5.2768 Initialized
[20:26:29] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[20:26:29] [main/INFO] [FML]: Replaced 1036 ore ingredients
[20:26:30] [main/INFO] [FML]: Searching C:\Users\Owner\AppData\Roaming\.minecraft\mods for mods
[20:26:31] [main/WARN] [FML]: Mod betterportals is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 0.3.7.4
[20:26:32] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 116347100 nanos
[20:26:32] [main/INFO] [FML]: Forge Mod Loader has identified 12 mods to load
[20:26:32] [main/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod ichunutil (iChunUtil) requires [forge@[14.23.5.2781,99999.24.0.0)]
[20:26:32] [main/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod ichunutil (iChunUtil) requires [forge@[14.23.5.2781,99999.24.0.0)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[20:26:32] [main/WARN] [FML]: EventBus 0 shutting down - future events will not be posted.
[20:26:32] [main/INFO] [net.minecraft.client.resources.SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:RandomPatches, FMLFileResourcePack:Better Portals, FMLFileResourcePack:Blockcraftery, FMLFileResourcePack:Shadowfacts' Forgelin, FMLFileResourcePack:GeneralLaymansAestheticSpyingScreen, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Mystical Lib, FMLFileResourcePack:RandomPortals
[20:26:33] [main/WARN] [FML]: There were errors previously. Not beginning mod initialization phase
[20:26:34] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[20:26:34] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[20:26:34] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[20:26:35] [Thread-5/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[20:26:35] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[20:26:35] [main/INFO] [com.mojang.text2speech.NarratorWindows]: Narrator library for x64 successfully loaded

**Comment by iChun** [comment]
Update your version of forge.
