### ISSUE TITLE
forge crashes on launch as soon as i have ichunutil (i think thats why)

### ISSUE THREAD

**Issue by dogewasfound** [iChun/iChunUtil#216]
heres the crash report

**---- Minecraft Crash Report ----

WARNING: coremods are present:
  Chiseled Me ASM (chiseled-me-1.12.2-2.0.0.1 (1).jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre324_mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.45_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 3/13/21 8:03 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer dev.necauqua.mods.cm.asm.Plugin@75dbf41c from coremod Chiseled Me ASM
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 16 more
Caused by: java.lang.IllegalStateException: Coremod failed!
Some patches were not applied to class EntityRenderer:
  transformer 'cameraView':
    method func_78479_a(FI)V:
      - <insert before INVOKESPECIAL net/minecraft/client/renderer/EntityRenderer.func_78475_f(F)V>
      - <insert after INVOKESPECIAL net/minecraft/client/renderer/EntityRenderer.func_78475_f(F)V>

	at dev.necauqua.mods.cm.asm.dsl.ASM.checkMisses(ASM.java:182)
	at dev.necauqua.mods.cm.asm.dsl.ASM.doTransform(ASM.java:129)
	at dev.necauqua.mods.cm.asm.Plugin.transform(Plugin.java:40)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:808)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 412163656 bytes (393 MB) / 671088640 bytes (640 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                  | Version      | Source                                               | Signature                                |
	|:----- |:----------------------------------- |:------------ |:---------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                           | 1.12.2       | minecraft.jar                                        | None                                     |
	| LC    | mcp                                 | 9.42         | minecraft.jar                                        | None                                     |
	| LC    | FML                                 | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                               | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy                   | 1.0.0        | minecraft.jar                                        | None                                     |
	| LC    | littletilescore                     | 1.0.0        | minecraft.jar                                        | None                                     |
	| LC    | securitycraft                       | v1.8.19      | [1.12.2]+SecurityCraft+v1.8.19.jar                   | None                                     |
	| LC    | chiseled_me                         | 2.0.0.1      | chiseled-me-1.12.2-2.0.0.1 (1).jar                   | c677c954974252994736eb15e855e1e6fc5a2e62 |
	| LC    | chiselsandbits                      | 14.33        | chiselsandbits-14.33 (1).jar                         | None                                     |
	| LC    | creativecore                        | 1.10.0       | CreativeCore_v1.10.45_mc1.12.2.jar                   | None                                     |
	| LC    | ichunutil                           | 7.2.2        | iChunUtil-1.12.2-7.2.2 (1).jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | generallaymansaestheticspyingscreen | 7.0.0        | GeneralLaymansAestheticSpyingScreen-1.12.2-7.0.0.jar | None                                     |
	| LC    | jei                                 | 4.15.0.291   | jei-1-12-2-4-15-0-291-jar.jar                        | None                                     |
	| LC    | littletiles                         | 1.5.0        | LittleTiles_v1.5.0-pre324_mc1.12.2.jar               | None                                     |
	| LC    | locks                               | 2.4          | locks-1.12.2-2.4.jar                                 | None                                     |

	Loaded coremods (and transformers): 
Chiseled Me ASM (chiseled-me-1.12.2-2.0.0.1 (1).jar)
  dev.necauqua.mods.cm.asm.Plugin
LittlePatchingLoader (LittleTiles_v1.5.0-pre324_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore_v1.10.45_mc1.12.2.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.5070' Renderer: 'Intel(R) HD Graphics 4600'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.5070, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Tommy_300k.zip (incompatible)
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz**

im not  a coder so i dont understand this

**Comment by DogeWasTakenWasTaken** [comment]
lemme rename that


forge crashes when i start because of ichunutil

i think

**Comment by iChun** [comment]
The crash log hints that it's caused by the mod which has the package
dev.necauqua.mods.cm

Doesn't seem to be an iChunUtil crash.

**Comment by dogewasfound** [comment]
ok
so i dont understand
can you name a list of mods that have that so i can delete it?
(if you find one)

**Comment by iChun** [comment]
Google says its "chiseled me"
