### ISSUE TITLE
Error about HeadGhast

### ISSUE THREAD

**Issue by dpeter99** [iChun/iChunUtil#221]
I'm using: ``iChunUtil-1.16.5-10.3.0.jar``

And getting the folowing error in the console.

```
[15:36:29] [Worker-Main-9/ERROR]: Cannot find custom head info class: me.ichun.mods.ichunutil.common.head.entity.HeadGhast
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: java.lang.ClassNotFoundException: me.ichun.mods.ichunutil.common.head.entity.HeadGhast
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at java.lang.Class.forName0(Native Method)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at java.lang.Class.forName(Class.java:264)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer.deserialize(HeadInfo.java:647)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer.deserialize(HeadInfo.java:531)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at com.google.gson.Gson.fromJson(Gson.java:887)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at com.google.gson.Gson.fromJson(Gson.java:852)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at com.google.gson.Gson.fromJson(Gson.java:801)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at com.google.gson.Gson.fromJson(Gson.java:773)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at me.ichun.mods.ichunutil.common.head.HeadHandler.loadHeadInfo(HeadHandler.java:293)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at me.ichun.mods.ichunutil.common.head.HeadHandler.readHeadInfoJson(HeadHandler.java:280)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at me.ichun.mods.ichunutil.common.head.HeadHandler.scourDirectory(HeadHandler.java:239)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at me.ichun.mods.ichunutil.common.head.HeadHandler.scourDirectory(HeadHandler.java:232)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at me.ichun.mods.ichunutil.common.head.HeadHandler.loadHeadInfos(HeadHandler.java:179)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at me.ichun.mods.ichunutil.common.head.HeadHandler.init(HeadHandler.java:112)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at me.ichun.mods.hats.common.Hats.finishLoading(Hats.java:198)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at me.ichun.mods.hats.common.Hats$$Lambda$3959/1199415911.accept(Unknown Source)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at net.minecraftforge.eventbus.EventBus$$Lambda$2910/319450809.invoke(Unknown Source)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at net.minecraftforge.eventbus.EventBus$$Lambda$2546/279767282.invoke(Unknown Source)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at net.minecraftforge.fml.ModContainer$$Lambda$3688/1423372658.run(Unknown Source)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
[15:36:29] [Worker-Main-9/INFO]: [me.ichun.mods.ichunutil.api.common.head.HeadInfo$Serializer:deserialize:676]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by iChun** [comment]
Delete the files in /config/ichunutil/head and let the mod reextract them.
Should fix this.
